#!/usr/bin/env bash

if [ "$#" -lt "2" ]; then
  echo "Usage: i3idle SECONDS COMMAND..."
  exit 1
fi

timeout="$(($1*1000))"
shift
command="$*"

echo "Timeout (secs): $timeout"
echo "Command: $command"

dorun=true

while true; do
  if [ "$(xprintidle)" -gt "$timeout" ]; then
    if $dorun; then 
      dorun=false
      $command 
    fi
  else
    dorun=true
  fi
  sleep 1
done
